version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      
  homecooking-ui:
    image: ${DOCKER_REGISTRY-}homecooking-ui:dev
    build:
      context: ./HomeCooking.Ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  homecooking-ui-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "homecooking-ui", "-app-port", "80" ]
    depends_on:
      - homecooking-ui
    network_mode: "service:homecooking-ui"

  homecooking-app:
    image: ${DOCKER_REGISTRY-}homecooking-app:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  homecooking-app-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", 
                "-app-id", "homecooking-app", 
                "-app-port", "80",
                "-components-path", "/dapr"       
              ]
    volumes:
      - "./dapr/:/dapr"  
    depends_on:
      - homecooking-app
    network_mode: "service:homecooking-app"

  logging-app:
    image: ${DOCKER_REGISTRY-}logging-app:dev
    build:
      context: ./HomeCooking.Logging
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  logging-app-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
               "-app-id", "logging-app",
               "-app-port", "80"
    ]
    depends_on:
      - logging-app
    network_mode: "service:logging-app"
