version: '3.4'

services:
  recipe-ui:
    image: ${DOCKER_REGISTRY-}recipe-ui:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  recipe-ui-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "recipe-ui", "-app-port", "80" ]
    depends_on:
      - recipe-ui
    network_mode: "service:recipe-ui"

  recipe-app:
    image: ${DOCKER_REGISTRY-}recipe-app:dev
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:80"

  recipe-app-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "recipe-app", "-app-port", "80" ]
    depends_on:
      - recipe-app
    network_mode: "service:recipe-app"